import { Button, Card, Text } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { priceDetails } from "../data";
import ItemCard, { ItemType } from "../components/ItemCard";

export default function Home() {
  return (
    <>
         <Head>
          <title>Gifti | Prices & Sizes</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    
      <div className={styles.header}>

        <h3 className={styles.logo}>Gifti.lk</h3>
      </div>
      <h1 className={styles.title}>FRAME SIZES</h1>
     
     
        
        <main className={styles.main}>
         
          {priceDetails.map((item: ItemType, i) => (
            <ItemCard item={item} key={i} />
          ))}
        </main>
     
    </>
  );
}
