import { Button, Card, Text } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AiOutlineBorderlessTable } from "react-icons/ai";
import { BsFillCheckCircleFill } from "react-icons/bs";
import { ImWhatsapp } from "react-icons/im";
import { priceDetails } from "../data";
import ItemCard, { ItemType } from "../components/ItemCard";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Gifty | Prices & Sizes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Prices & Sizes</h1>
                {priceDetails.map((item: ItemType, i) => (
                    <ItemCard item={item} key={i} />
                ))}
            </main>
        </div>
    );
}
